// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bh.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	bh.proto

It has these top-level messages:
	BhBlock
	BhFile
	BhBlockData
	BhMessage
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BhMessage_BhMessageType int32

const (
	BhMessage_BH_PING     BhMessage_BhMessageType = 1
	BhMessage_BH_PEERS    BhMessage_BhMessageType = 2
	BhMessage_BH_INDEX    BhMessage_BhMessageType = 3
	BhMessage_BH_REQUEST  BhMessage_BhMessageType = 4
	BhMessage_BH_RESPONSE BhMessage_BhMessageType = 5
)

var BhMessage_BhMessageType_name = map[int32]string{
	1: "BH_PING",
	2: "BH_PEERS",
	3: "BH_INDEX",
	4: "BH_REQUEST",
	5: "BH_RESPONSE",
}
var BhMessage_BhMessageType_value = map[string]int32{
	"BH_PING":     1,
	"BH_PEERS":    2,
	"BH_INDEX":    3,
	"BH_REQUEST":  4,
	"BH_RESPONSE": 5,
}

func (x BhMessage_BhMessageType) Enum() *BhMessage_BhMessageType {
	p := new(BhMessage_BhMessageType)
	*p = x
	return p
}
func (x BhMessage_BhMessageType) String() string {
	return proto.EnumName(BhMessage_BhMessageType_name, int32(x))
}
func (x *BhMessage_BhMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BhMessage_BhMessageType_value, data, "BhMessage_BhMessageType")
	if err != nil {
		return err
	}
	*x = BhMessage_BhMessageType(value)
	return nil
}
func (BhMessage_BhMessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type BhBlock struct {
	Offset           *uint64 `protobuf:"varint,1,req,name=offset" json:"offset,omitempty"`
	Length           *uint32 `protobuf:"varint,2,req,name=length" json:"length,omitempty"`
	Hash             []byte  `protobuf:"bytes,3,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BhBlock) Reset()                    { *m = BhBlock{} }
func (m *BhBlock) String() string            { return proto.CompactTextString(m) }
func (*BhBlock) ProtoMessage()               {}
func (*BhBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BhBlock) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *BhBlock) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *BhBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BhFile struct {
	Name             []byte     `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Flags            *uint32    `protobuf:"varint,2,req,name=flags" json:"flags,omitempty"`
	Modified         *int64     `protobuf:"varint,3,req,name=modified" json:"modified,omitempty"`
	Blocks           []*BhBlock `protobuf:"bytes,4,rep,name=blocks" json:"blocks,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *BhFile) Reset()                    { *m = BhFile{} }
func (m *BhFile) String() string            { return proto.CompactTextString(m) }
func (*BhFile) ProtoMessage()               {}
func (*BhFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BhFile) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *BhFile) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *BhFile) GetModified() int64 {
	if m != nil && m.Modified != nil {
		return *m.Modified
	}
	return 0
}

func (m *BhFile) GetBlocks() []*BhBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type BhBlockData struct {
	Name             []byte   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Offset           *uint64  `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	Length           *uint32  `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	Hash             []byte   `protobuf:"bytes,4,req,name=hash" json:"hash,omitempty"`
	Data             [][]byte `protobuf:"bytes,5,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BhBlockData) Reset()                    { *m = BhBlockData{} }
func (m *BhBlockData) String() string            { return proto.CompactTextString(m) }
func (*BhBlockData) ProtoMessage()               {}
func (*BhBlockData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BhBlockData) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *BhBlockData) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *BhBlockData) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *BhBlockData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BhBlockData) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BhMessage struct {
	Type             *BhMessage_BhMessageType `protobuf:"varint,1,req,name=type,enum=main.BhMessage_BhMessageType" json:"type,omitempty"`
	Updated          *int64                   `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
	Peers            []*BhMessage_Peer        `protobuf:"bytes,3,rep,name=peers" json:"peers,omitempty"`
	Files            []*BhFile                `protobuf:"bytes,4,rep,name=files" json:"files,omitempty"`
	BlockData        *BhBlockData             `protobuf:"bytes,5,opt,name=blockData" json:"blockData,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *BhMessage) Reset()                    { *m = BhMessage{} }
func (m *BhMessage) String() string            { return proto.CompactTextString(m) }
func (*BhMessage) ProtoMessage()               {}
func (*BhMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BhMessage) GetType() BhMessage_BhMessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BhMessage_BH_PING
}

func (m *BhMessage) GetUpdated() int64 {
	if m != nil && m.Updated != nil {
		return *m.Updated
	}
	return 0
}

func (m *BhMessage) GetPeers() []*BhMessage_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *BhMessage) GetFiles() []*BhFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *BhMessage) GetBlockData() *BhBlockData {
	if m != nil {
		return m.BlockData
	}
	return nil
}

type BhMessage_Peer struct {
	Id               []byte   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Addrs            [][]byte `protobuf:"bytes,2,rep,name=addrs" json:"addrs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BhMessage_Peer) Reset()                    { *m = BhMessage_Peer{} }
func (m *BhMessage_Peer) String() string            { return proto.CompactTextString(m) }
func (*BhMessage_Peer) ProtoMessage()               {}
func (*BhMessage_Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *BhMessage_Peer) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *BhMessage_Peer) GetAddrs() [][]byte {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func init() {
	proto.RegisterType((*BhBlock)(nil), "main.BhBlock")
	proto.RegisterType((*BhFile)(nil), "main.BhFile")
	proto.RegisterType((*BhBlockData)(nil), "main.BhBlockData")
	proto.RegisterType((*BhMessage)(nil), "main.BhMessage")
	proto.RegisterType((*BhMessage_Peer)(nil), "main.BhMessage.Peer")
	proto.RegisterEnum("main.BhMessage_BhMessageType", BhMessage_BhMessageType_name, BhMessage_BhMessageType_value)
}

func init() { proto.RegisterFile("bh.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x51, 0x6b, 0xdb, 0x30,
	0x10, 0xc7, 0x89, 0x24, 0x27, 0xe9, 0x39, 0xc9, 0xbc, 0xa3, 0x0c, 0x51, 0x18, 0x18, 0xc3, 0xc0,
	0x8c, 0x91, 0xb1, 0x7c, 0x04, 0x53, 0x6f, 0xed, 0x43, 0xb3, 0x4c, 0xee, 0x60, 0x7b, 0x2a, 0xca,
	0x24, 0xc7, 0x66, 0x4e, 0x6c, 0x6c, 0xf7, 0x21, 0x5f, 0x77, 0x9f, 0x64, 0xc8, 0x96, 0x67, 0x3a,
	0xda, 0xb7, 0xfb, 0xdd, 0x1d, 0x77, 0xf7, 0xff, 0x1f, 0xcc, 0xf7, 0xd9, 0xba, 0xaa, 0xcb, 0xb6,
	0x44, 0x76, 0x94, 0xf9, 0x29, 0xb8, 0x83, 0x59, 0x94, 0x45, 0x45, 0xf9, 0xeb, 0x37, 0xbe, 0x81,
	0x69, 0x99, 0xa6, 0x8d, 0x6e, 0xf9, 0xc4, 0x27, 0x21, 0x13, 0x96, 0x4c, 0xbe, 0xd0, 0xa7, 0x43,
	0x9b, 0x71, 0xe2, 0x93, 0x70, 0x29, 0x2c, 0x21, 0x02, 0xcb, 0x64, 0x93, 0x71, 0xea, 0x93, 0x70,
	0x21, 0xba, 0x38, 0x78, 0x84, 0x69, 0x94, 0x7d, 0xce, 0x0b, 0x6d, 0xaa, 0x27, 0x79, 0xd4, 0xdd,
	0xac, 0x85, 0xe8, 0x62, 0xbc, 0x04, 0x27, 0x2d, 0xe4, 0xa1, 0xb1, 0x83, 0x7a, 0xc0, 0x2b, 0x98,
	0x1f, 0x4b, 0x95, 0xa7, 0xb9, 0x56, 0xdd, 0x2c, 0x2a, 0xfe, 0x31, 0xbe, 0x83, 0xe9, 0xde, 0x1c,
	0xd7, 0x70, 0xe6, 0xd3, 0xd0, 0xdd, 0x2c, 0xd7, 0xe6, 0xea, 0xb5, 0x3d, 0x59, 0xd8, 0x62, 0x70,
	0x06, 0xd7, 0xa6, 0xae, 0x65, 0x2b, 0x9f, 0xdd, 0x3d, 0xaa, 0x23, 0x2f, 0xa8, 0xa3, 0xcf, 0xaa,
	0x63, 0xa3, 0x3a, 0x93, 0x53, 0xb2, 0x95, 0xdc, 0xf1, 0xa9, 0xc9, 0x99, 0x38, 0xf8, 0x43, 0xe0,
	0x22, 0xca, 0xee, 0x74, 0xd3, 0xc8, 0x83, 0xc6, 0x4f, 0xc0, 0xda, 0x73, 0xd5, 0x6f, 0x5e, 0x6d,
	0xde, 0x0e, 0xd7, 0xda, 0xf2, 0x18, 0xdd, 0x9f, 0x2b, 0x2d, 0xba, 0x56, 0xe4, 0x30, 0x7b, 0xac,
	0x94, 0x6c, 0xb5, 0xe2, 0xc4, 0x9f, 0x84, 0x54, 0x0c, 0x88, 0xef, 0xc1, 0xa9, 0xb4, 0xae, 0x1b,
	0x4e, 0x3b, 0xed, 0x97, 0xff, 0x4f, 0xdb, 0x69, 0x5d, 0x8b, 0xbe, 0x05, 0x03, 0x70, 0xd2, 0xbc,
	0xd0, 0x83, 0x4f, 0x8b, 0xa1, 0xd7, 0xfc, 0x42, 0xf4, 0x25, 0xfc, 0x08, 0x17, 0xfb, 0xc1, 0x23,
	0xee, 0xf8, 0x93, 0xd0, 0xdd, 0xbc, 0x7e, 0xe2, 0xa7, 0x29, 0x88, 0xb1, 0xe7, 0xea, 0x03, 0x30,
	0xb3, 0x03, 0x57, 0x40, 0x72, 0x65, 0xdd, 0x24, 0xb9, 0x32, 0x7f, 0x94, 0x4a, 0xd5, 0xe6, 0x8f,
	0xc6, 0x88, 0x1e, 0x82, 0x9f, 0xb0, 0x7c, 0xa2, 0x0f, 0x5d, 0x98, 0x45, 0x37, 0x0f, 0xbb, 0xdb,
	0xed, 0x17, 0x6f, 0x82, 0x0b, 0x98, 0x1b, 0x88, 0x63, 0x91, 0x78, 0xc4, 0xd2, 0xed, 0xf6, 0x3a,
	0xfe, 0xe1, 0x51, 0x5c, 0x01, 0x44, 0x37, 0x0f, 0x22, 0xfe, 0xf6, 0x3d, 0x4e, 0xee, 0x3d, 0x86,
	0xaf, 0xc0, 0xed, 0x38, 0xd9, 0x7d, 0xdd, 0x26, 0xb1, 0xe7, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x46, 0x68, 0xf8, 0xb7, 0xb6, 0x02, 0x00, 0x00,
}
